import assert from "node:assert/strict";
import { chmodSync, cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
// @ts-expect-error Unshipped JavaScript commands have no declaration files.
import { abandon, advance, authorizeInstall, authorizeUpload, beginPromotion, beginUpload, claimRelease, classifyRegistry, closeWithoutPromotion, hashBytes, initialState, makeRequest, planFinalization, recordInstallFailure, recordInstallProof, recordPromotion, recordRegistry, retire, verifyReleaseIdentity, writeExclusive } from "../verification/release-control.mjs";
// @ts-expect-error Unshipped JavaScript commands have no declaration files.
import { executeFinalRecords, executeInstall, executePromotion, executeUpload } from "../verification/release-job.mjs";

const A="a".repeat(40),B="b".repeat(40),C="c".repeat(40),NOW="2026-09-17T00:00:00.000Z",notes="Release notes\n";
const req=(current="0.10.0",text=notes,authorization="101")=>makeRequest({version:"0.10.1",baseSha:A,notes:text,currentVersion:current,authorization});
const claimed=(request=req())=>claimRelease(initialState(request,NOW),{request,releaseSha:B,parentSha:A,pullRequest:9,runId:"17",runAttempt:"1"},NOW);
const owner=(state=claimed())=>({identity:state.identity,version:state.version,releaseSha:state.releaseSha,releaseParent:state.releaseParent});
const ready=(request=req())=>{const s=claimed(request),o=owner(s);return advance(advance(s,"checking",o,NOW),"ready",o,NOW);};
const uploaded=(request=req())=>{const s=ready(request),o=owner(s);return beginUpload(s,{file:"package.tgz",...hashBytes(Buffer.from("archive"))},o,"17","1",NOW);};
const published=()=>{const s=uploaded(),o=owner(s),bytes=Buffer.from("archive"),result=classifyRegistry(s,bytes,bytes,{version:s.version,integrity:hashBytes(bytes).integrity},o);return recordRegistry(s,result,o,NOW);};
const installEnvelope=(s:any,execution="17:1")=>({identity:s.identity,version:s.version,releaseSha:s.releaseSha,releaseParent:s.releaseParent,execution,registryIntegrity:s.registry.integrity,proof:{command:"slate",source:`npm:ytdb-slate@${s.version}`}});
const failureEnvelope=(s:any,execution="17:1",failure="command-proof")=>({identity:s.identity,version:s.version,releaseSha:s.releaseSha,releaseParent:s.releaseParent,execution,registryIntegrity:s.registry.integrity,result:"failed",failure});
const failedPublished=()=>{const s=published();return recordInstallFailure(s,failureEnvelope(s),owner(s),NOW);};
const proved=()=>{const s=published();return recordInstallProof(s,installEnvelope(s),owner(s),NOW);};
const identity=(request=req())=>({request,durableRequest:structuredClone(request),coverageRecord:{schema:2,parentPolicy:"exact-release-parent",allowedPaths:request.coverageDisposition.allowedPaths,verdict:"WARN"},notes,releaseSha:B,parentSha:A,changedPaths:request.coverageDisposition.allowedPaths,manifestVersion:"0.10.1",associatedPullRequests:[{number:9,merged:true,mergeCommitSha:B,baseRefName:"main"}]});

test("exact merge identity supports grouped pushes, correction, and fresh generations",()=>{assert.equal(verifyReleaseIdentity(identity()).pullRequest,9);const correction=req("0.10.1");assert.equal(correction.coverageDisposition.allowedPaths.length,3);assert.equal(verifyReleaseIdentity(identity(correction)).identity,correction.identity);assert.notEqual(C,verifyReleaseIdentity(identity()).releaseSha);const fresh=req("0.10.0",notes,"102");assert.notEqual(fresh.identity,req().identity);for(const mutate of[(x:any)=>x.notes="changed",(x:any)=>x.durableRequest=req("0.10.0","other\n"),(x:any)=>x.changedPaths=["extension/index.ts"],(x:any)=>x.associatedPullRequests=[]]){const x:any=identity();mutate(x);assert.throws(()=>verifyReleaseIdentity(x));}});

test("abandon then identical preparation creates a fresh authorization and rejects the old generation",()=>{const first=req(),terminal=abandon(initialState(first,NOW),{identity:first.identity,version:first.version,releaseSha:null,releaseParent:null},false,NOW),second=req("0.10.0",notes,"102");assert.equal(terminal.status,"abandoned");assert.notEqual(second.identity,first.identity);const merged=claimed(second);assert.equal(merged.status,"claimed");assert.throws(()=>advance(merged,"checking",{...owner(merged),identity:first.identity},NOW));});

test("claim and retirement require independently supplied identity",()=>{const request=req(),first=claimed(request),again=claimRelease(first,{request,releaseSha:B,parentSha:A,pullRequest:9,runId:"17",runAttempt:"2"},NOW);assert.deepEqual(again,first);assert.throws(()=>claimRelease(initialState(req("0.10.0",notes,"102"),NOW),{request,releaseSha:B,parentSha:A,pullRequest:9,runId:"17",runAttempt:"1"},NOW));assert.throws(()=>retire(first,{...owner(first),identity:"f".repeat(64)},NOW));assert.equal(retire(first,owner(first),NOW).status,"retired");});

test("every upload stage rejects stale identity, execution, and prior upload",()=>{const s=ready(),o=owner(s),artifact={file:"package.tgz",...hashBytes(Buffer.from("archive"))};assert.throws(()=>beginUpload(s,artifact,{...o,identity:"f".repeat(64)},"17","1",NOW));const u=beginUpload(s,artifact,o,"17","1",NOW);assert.equal(authorizeUpload(u,o,"17","1").version,"0.10.1");assert.throws(()=>authorizeUpload(u,o,"17","2"));assert.throws(()=>beginUpload({...s,upload:"verified"},artifact,o,"17","1",NOW));const bytes=Buffer.from("archive");assert.throws(()=>classifyRegistry(u,bytes,bytes,{version:u.version,integrity:hashBytes(bytes).integrity},{...o,identity:"f".repeat(64)}));const result=classifyRegistry(u,bytes,bytes,{version:u.version,integrity:hashBytes(bytes).integrity},o);assert.throws(()=>recordRegistry(u,result,{...o,identity:"f".repeat(64)},NOW));assert.throws(()=>recordRegistry(u,{...result,identity:"e".repeat(64)},o,NOW));assert.throws(()=>recordRegistry(u,{...result,execution:"17:2"},o,NOW));assert.equal(recordRegistry(u,result,o,NOW).status,"published");});

test("registry outcomes preserve unknown attribution",()=>{const s=uploaded(),o=owner(s),bytes=Buffer.from("archive"),metadata={version:s.version,integrity:hashBytes(bytes).integrity};const mismatch=classifyRegistry(s,bytes,Buffer.from("other"),metadata,o);assert.deepEqual({result:mismatch.result,attribution:mismatch.attribution},{result:"mismatch",attribution:"unknown"});assert.equal(recordRegistry(s,mismatch,o,NOW).status,"mismatch");assert.equal(classifyRegistry(s,bytes,Buffer.alloc(0),null,o).result,"inconclusive");});

test("install and promotion recorders reject stale artifacts and wrong verified result",()=>{const p=published(),o=owner(p),proof=installEnvelope(p);assert.throws(()=>recordInstallProof(p,proof,{...o,identity:"f".repeat(64)},NOW));assert.throws(()=>recordInstallProof(p,{...proof,identity:"f".repeat(64)},o,NOW));assert.throws(()=>recordInstallProof(p,{...proof,version:"0.10.2"},o,NOW));assert.throws(()=>recordInstallProof(p,{...proof,releaseParent:C},o,NOW));assert.throws(()=>recordInstallProof(p,{...proof,registryIntegrity:"sha512-foreign"},o,NOW));assert.throws(()=>recordInstallProof(p,{...proof,execution:"bad"},o,NOW));const provedState=recordInstallProof(p,proof,o,NOW),intent=beginPromotion(provedState,"0.10.0",o,"17","1",NOW),po=owner(intent),base={identity:intent.identity,releaseSha:intent.releaseSha,execution:"17:1"};assert.throws(()=>recordPromotion(intent,{...base,result:"conflict",after:"0.10.2"},{...po,identity:"f".repeat(64)},NOW));assert.throws(()=>recordPromotion(intent,{...base,result:"verified",before:"0.10.0",after:"0.10.2"},po,NOW));assert.throws(()=>recordPromotion(intent,{...base,execution:"17:2",result:"conflict",after:"0.10.2"},po,NOW));const conflict=recordPromotion(intent,{...base,result:"conflict",before:"0.10.2",after:"0.10.2"},po,NOW);assert.equal(conflict.promotion,"conflict");assert.throws(()=>closeWithoutPromotion({...conflict,promoterExecution:"19:1"},owner(conflict),NOW));assert.throws(()=>closeWithoutPromotion(conflict,{...owner(conflict),identity:"f".repeat(64)},NOW));assert.throws(()=>closeWithoutPromotion(conflict,{...owner(conflict),version:"0.10.2"},NOW));assert.equal(closeWithoutPromotion(conflict,owner(conflict),NOW).status,"closed-unpromoted");assert.throws(()=>closeWithoutPromotion(intent,owner(intent),NOW));const promoted=recordPromotion(intent,{...base,result:"verified",before:"0.10.0",after:"0.10.1"},po,NOW);assert.equal(planFinalization({state:promoted,expected:owner(promoted),remoteTagSha:"",releaseTarget:""}).createTag,true);});

test("operator actions bind version and generation without mutating the wrong state",()=>{const prepared=initialState(req(),NOW),target={identity:prepared.identity,version:prepared.version,releaseSha:null,releaseParent:null};assert.throws(()=>abandon(prepared,{...target,version:"0.10.2"},false,NOW));assert.throws(()=>abandon(prepared,{...target,identity:"f".repeat(64)},false,NOW));assert.equal(abandon(prepared,target,false,NOW).status,"abandoned");assert.throws(()=>abandon(prepared,target,true,NOW));const c=claimed();assert.throws(()=>retire(c,{...owner(c),version:"0.10.2"},NOW));assert.throws(()=>retire(c,{...owner(c),identity:"f".repeat(64)},NOW));});

test("install failure evidence permits only explicit terminal closure and preserves retry history",()=>{const pub=published(),o=owner(pub),auth=authorizeInstall(pub,o,"17","2");assert.equal(auth.execution,"17:2");for(const mutate of[(s:any)=>({...s,status:"proved"}),(s:any)=>({...s,registry:null}),(s:any)=>({...s,upload:"unknown"}),(s:any)=>({...s,registry:{...s.registry,identity:"f".repeat(64)}}),(s:any)=>({...s,registry:{...s.registry,releaseSha:C}}),(s:any)=>({...s,registry:{...s.registry,execution:"17:2"}})])assert.throws(()=>authorizeInstall(mutate(pub),o,"17","2"));const failure=failureEnvelope(pub,"17:2"),failed=recordInstallFailure(pub,failure,o,NOW);assert.equal(failed.installFailures.length,1);assert.deepEqual(recordInstallFailure(failed,failure,o,NOW),failed);assert.throws(()=>recordInstallFailure(pub,{...failure,registryIntegrity:"sha512-foreign"},o,NOW));assert.throws(()=>recordInstallFailure(pub,{...failure,identity:"f".repeat(64)},o,NOW));const unchanged=JSON.stringify(failed);assert.throws(()=>closeWithoutPromotion(pub,o,NOW));assert.throws(()=>closeWithoutPromotion(uploaded(),owner(uploaded()),NOW));assert.throws(()=>closeWithoutPromotion({...failed,promotion:"unknown"},o,NOW));assert.throws(()=>closeWithoutPromotion({...failed,promoterExecution:"19:1"},o,NOW));assert.throws(()=>closeWithoutPromotion(failed,{...o,version:"0.10.2"},NOW));assert.equal(JSON.stringify(failed),unchanged);const closed=closeWithoutPromotion(failed,o,NOW);assert.equal(closed.status,"closed-unpromoted");assert.equal(closed.installFailures.length,1);assert.throws(()=>recordInstallFailure(closed,failure,o,NOW));assert.throws(()=>recordInstallProof(closed,installEnvelope(pub,"17:3"),o,NOW));const proof=installEnvelope(failed,"17:3"),retry=recordInstallProof(failed,proof,o,NOW);assert.equal(retry.status,"proved");assert.equal(retry.installFailures.length,1);assert.throws(()=>recordInstallFailure(retry,failureEnvelope(pub,"17:4"),o,NOW));const later=makeRequest({version:"0.10.2",baseSha:B,notes,currentVersion:"0.10.1",authorization:"102"});assert.equal(initialState(later,NOW).version,"0.10.2");});

test("release effects use exact commands and reject stale launch identity before effects",()=>{const calls:any[]=[],u=uploaded(),o=owner(u),root=mkdtempSync(join(tmpdir(),"slate-upload-")),archive=join(root,"package.tgz");writeFileSync(archive,"archive");try{assert.throws(()=>executeUpload({state:u,expected:{...o,identity:"f".repeat(64)},archive,runId:"17",runAttempt:"1",registry:"https://registry.invalid/",npmVersion:()=>"11.16.0",exec:(...x:any[])=>calls.push(x)}));executeUpload({state:u,expected:o,archive,runId:"17",runAttempt:"1",registry:"https://registry.invalid/",npmVersion:()=>"11.16.0",exec:(...x:any[])=>calls.push(x)});}finally{rmSync(root,{recursive:true,force:true});}assert.deepEqual(calls[0][1],["publish",archive,"--tag","slate-candidate","--ignore-scripts","--provenance=false","--registry","https://registry.invalid/"]);
const ps=proved(),intent=beginPromotion(ps,"0.10.0",owner(ps),"17","1",NOW);let views=0;const result=executePromotion({state:intent,expected:owner(intent),runId:"17",runAttempt:"1",registry:"https://registry.invalid/",token:"secret",view:()=>views++===0?"0.10.0":"0.10.1",exec:(...x:any[])=>calls.push(x)});assert.equal(result.execution,"17:1");assert.throws(()=>executePromotion({state:intent,expected:{...owner(intent),identity:"f".repeat(64)},runId:"17",runAttempt:"1",registry:"x",token:"secret",view:()=>assert.fail(),exec:()=>assert.fail()}));
const pub=published(),installRoot=mkdtempSync(join(tmpdir(),"slate-install-"));try{let wrongN=0;assert.throws(()=>executeInstall({state:pub,expected:{...owner(pub),identity:"f".repeat(64)},runId:"17",runAttempt:"2",workspace:installRoot,out:join(installRoot,"wrong.json"),exec:()=>{wrongN++;return{stdout:""};}}));assert.equal(wrongN,0);let n=0;const proof=executeInstall({state:pub,expected:owner(pub),runId:"17",runAttempt:"2",workspace:installRoot,out:join(installRoot,"proof.json"),exec:()=>++n===2?{stdout:'{"type":"response","command":"get_commands","data":{"commands":[{"name":"slate","sourceInfo":{"source":"npm:ytdb-slate@0.10.1"}}]}}\n'}:{stdout:""}});assert.equal(proof.identity,pub.identity);assert.equal(proof.execution,"17:2");const retryProved=recordInstallProof(pub,proof,owner(pub),NOW);assert.equal(retryProved.status,"proved");assert.equal(beginPromotion(retryProved,"0.10.0",owner(retryProved),"18","1",NOW).status,"promotion-unknown");}finally{rmSync(installRoot,{recursive:true,force:true});}
const promoted=recordPromotion(intent,result,owner(intent),NOW);calls.length=0;executeFinalRecords({state:promoted,expected:owner(promoted),notes:"notes.md",repo:"JetBrains/ytdb-slate",exec:(...x:any[])=>calls.push(x)});assert.equal(calls.filter(x=>x[0]==="git").length,2);assert.equal(calls.filter(x=>x[0]==="gh").length,1);});

const workflowUrl=new URL("../.github/workflows/release.yml",import.meta.url),workflow=readFileSync(workflowUrl,"utf8"),releasing=readFileSync(new URL("../RELEASING.md",import.meta.url),"utf8"),agents=readFileSync(new URL("../AGENTS.md",import.meta.url),"utf8"),mechanism=readFileSync(new URL("../verification/README.md",import.meta.url),"utf8");
function workflowRunBlock(name:string){const lines=workflow.split("\n"),start=lines.findIndex(x=>x===`  ${name}:`);assert.notEqual(start,-1,`missing workflow job ${name}`);let end=lines.length;for(let i=start+1;i<lines.length;i++)if(/^  [a-z][a-z-]*:$/.test(lines[i]??"")){end=i;break;}const marker=lines.findIndex((x,i)=>i>start&&i<end&&["run: |","- run: |"].includes(x.trim()));assert.notEqual(marker,-1,`missing run block for ${name}`);const markerLine=lines[marker]??"",markerIndent=markerLine.length-markerLine.trimStart().length,body:string[]=[];for(let i=marker+1;i<end;i++){const line=lines[i]??"",indent=line.length-line.trimStart().length;if(line.trim()&&indent<=markerIndent)break;body.push(line);}const contentIndent=Math.min(...body.filter(x=>x.trim()).map(x=>x.length-x.trimStart().length));return body.map(x=>x.slice(Math.min(contentIndent,x.length))).join("\n");}
function renderWorkflowBlock(source:string,values:Record<string,string>={}){return source.replace(/\$\{\{\s*([^}]+?)\s*\}\}/g,(_all,key:string)=>{const value=values[key.trim()];if(value===undefined)throw new Error(`unknown workflow expression ${key}`);return value;});}
function workflowFixture(t:any,state:any){const root=mkdtempSync(join(tmpdir(),"slate-workflow-")),bin=join(root,"bin"),effectLog=join(root,"effects.log");t.after(()=>rmSync(root,{recursive:true,force:true}));mkdirSync(bin);mkdirSync(join(root,"verification"));mkdirSync(join(root,"control/verification"),{recursive:true});mkdirSync(join(root,"state/archive"),{recursive:true});for(const dir of["verification","control/verification"])for(const file of["release-control.mjs","release-job.mjs"])cpSync(new URL(`../verification/${file}`,import.meta.url),join(root,dir,file));writeFileSync(join(root,"state.json"),JSON.stringify(state,null,2)+"\n");writeFileSync(join(root,"state/state.json"),JSON.stringify(state,null,2)+"\n");writeFileSync(join(root,"state/archive/package.tgz"),"archive");writeFileSync(effectLog,"");writeFileSync(join(bin,"git"),`#!/bin/sh\nprintf 'git\\t%s\\n' "$*" >>"$EFFECT_LOG"\ncase "$*" in *"rev-parse HEAD"*) printf '${C}\\n';; esac\nexit 0\n`);writeFileSync(join(bin,"gh"),`#!/bin/sh\nprintf 'gh\\t%s\\n' "$*" >>"$EFFECT_LOG"\nexit 0\n`);writeFileSync(join(bin,"npm"),`#!/bin/sh\nprintf 'npm\\t%s\\n' "$*" >>"$EFFECT_LOG"\ncase "$*" in *"dist-tags.latest"*) printf '0.10.0\\n';; esac\nexit 0\n`);writeFileSync(join(bin,"pi"),`#!/bin/sh\nprintf 'pi\\t%s\\n' "$*" >>"$EFFECT_LOG"\ncase "$*" in *"--mode rpc"*) if test "${'${PI_SUCCESS:-0}'}" = 1; then printf '{"type":"response","command":"get_commands","data":{"commands":[{"name":"slate","sourceInfo":{"source":"npm:ytdb-slate@0.10.1"}}]}}\\n'; else printf '{"type":"response","command":"get_commands","data":{"commands":[]}}\\n'; fi;; esac\nexit 0\n`);for(const name of["git","gh","npm","pi"])chmodSync(join(bin,name),0o755);const env={PATH:`${bin}:${dirname(process.execPath)}:/usr/bin:/bin`,PI_BIN:join(bin,"pi"),HOME:root,RUNNER_TEMP:join(root,"runner"),GIT_CONFIG_NOSYSTEM:"1",GIT_CONFIG_GLOBAL:"/dev/null",EFFECT_LOG:effectLog,GITHUB_RUN_ID:"900",GITHUB_RUN_ATTEMPT:"2",GITHUB_REPOSITORY:"JetBrains/ytdb-slate",GITHUB_OUTPUT:join(root,"output")};return{root,effectLog,env};}
function runWorkflowBlock(f:any,script:string,more:Record<string,string>={}){return spawnSync("/bin/bash",["-c",script],{cwd:f.root,env:{...f.env,...more},encoding:"utf8",timeout:10000});}

const workflowValues=(state:any)=>({"needs.identify.outputs.identity":state.identity,"needs.identify.outputs.version":state.version,"needs.identify.outputs.release_sha":state.releaseSha,"needs.identify.outputs.parent_sha":state.releaseParent});

test("real seal-upload workflow block runs and requires identity at begin-upload",t=>{const state=claimed(),values=workflowValues(state),source=workflowRunBlock("seal-upload"),f=workflowFixture(t,state),result=runWorkflowBlock(f,renderWorkflowBlock(source,values));assert.equal(result.status,0,result.stderr);const sealed=JSON.parse(readFileSync(join(f.root,"state/state.json"),"utf8"));assert.equal(sealed.status,"upload-unknown");assert.equal(sealed.uploadExecution,"900:2");assert.match(readFileSync(f.effectLog,"utf8"),/push origin HEAD:release-state --force-with-lease=/);
const mutant=source.split("\n").map(line=>line.includes(" begin-upload ")?line.replace(" --identity '${{ needs.identify.outputs.identity }}'",""):line).join("\n");assert.notEqual(mutant,source);const mf=workflowFixture(t,state),failed=runWorkflowBlock(mf,renderWorkflowBlock(mutant,values));assert.notEqual(failed.status,0);assert.equal(JSON.parse(readFileSync(join(mf.root,"state/state.json"),"utf8")).status,"claimed");assert.doesNotMatch(readFileSync(mf.effectLog,"utf8"),/push origin/);});

test("real operator workflow blocks bind targets and permit intended progress",t=>{for(const [name,state,expectedStatus] of [["retire",claimed(),"retired"],["close",proved(),"closed-unpromoted"],["close",failedPublished(),"closed-unpromoted"]] as const){const script=workflowRunBlock(name);for(const [label,version,identity] of [["correct",state.version,state.identity],["wrong-version","0.10.2",state.identity],["wrong-identity",state.version,"f".repeat(64)]] as const){const f=workflowFixture(t,state),before=readFileSync(join(f.root,"state.json"),"utf8"),result=runWorkflowBlock(f,script,{VERSION:version,IDENTITY:identity}),effects=readFileSync(f.effectLog,"utf8");if(label==="correct"){assert.equal(result.status,0,`${name}: ${result.stderr}`);assert.equal(JSON.parse(readFileSync(join(f.root,"state.json"),"utf8")).status,expectedStatus);assert.match(effects,/push origin HEAD:release-state/);}else{assert.notEqual(result.status,0,`${name} accepted ${label}`);assert.equal(readFileSync(join(f.root,"state.json"),"utf8"),before);assert.doesNotMatch(effects,/git\t.*(?:add|commit|push)|gh\t|npm\t/);}}}
const state=published(),script=workflowRunBlock("recover");for(const [label,version,identity] of [["correct",state.version,state.identity],["wrong-version","0.10.2",state.identity],["wrong-identity",state.version,"f".repeat(64)]] as const){const f=workflowFixture(t,state),before=readFileSync(join(f.root,"state.json"),"utf8"),result=runWorkflowBlock(f,script,{VERSION:version,IDENTITY:identity}),effects=readFileSync(f.effectLog,"utf8");if(label==="correct"){assert.equal(result.status,0,result.stderr);assert.match(effects,/gh\trun rerun 17 --repo JetBrains\/ytdb-slate --failed/);assert.match(result.stdout,/failed jobs and their dependents/);assert.match(result.stdout,/Promotion and final records can run only after/);assert.doesNotMatch(result.stdout,/read-only installation proof|promotion remain disabled/i);}else{assert.notEqual(result.status,0);assert.doesNotMatch(effects,/gh\t|npm\t|git\t.*(?:add|commit|push)/);}assert.equal(readFileSync(join(f.root,"state.json"),"utf8"),before);}const unknown=uploaded(),uf=workflowFixture(t,unknown),before=readFileSync(join(uf.root,"state.json"),"utf8"),retried=runWorkflowBlock(uf,script,{VERSION:unknown.version,IDENTITY:unknown.identity});assert.equal(retried.status,0,retried.stderr);assert.match(readFileSync(uf.effectLog,"utf8"),/gh\trun rerun 17 --repo JetBrains\/ytdb-slate --failed/);assert.match(retried.stdout,/failed jobs and their dependents/);assert.match(retried.stdout,/sealed upload authority rejects every upload rerun/);assert.match(retried.stdout,/Promotion and final records can run only after registry and installation proofs succeed/);assert.equal(readFileSync(join(uf.root,"state.json"),"utf8"),before);});

test("real install failure workflow records the producing attempt and closes without success effects",t=>{const pub=published(),values=workflowValues(pub),install=renderWorkflowBlock(workflowRunBlock("install-proof"),values),f=workflowFixture(t,pub),failed=runWorkflowBlock(f,install);assert.notEqual(failed.status,0);const failurePath=join(f.root,"runner/install/failure.json"),failure=JSON.parse(readFileSync(failurePath,"utf8"));assert.equal(failure.execution,"900:2");assert.equal(failure.result,"failed");mkdirSync(join(f.root,"failure"));cpSync(failurePath,join(f.root,"failure/failure.json"));const recorded=runWorkflowBlock(f,renderWorkflowBlock(workflowRunBlock("record-install-failure"),values));assert.equal(recorded.status,0,recorded.stderr);const state=JSON.parse(readFileSync(join(f.root,"state.json"),"utf8"));assert.equal(state.status,"published");assert.equal(state.installFailures[0].execution,"900:2");assert.doesNotMatch(readFileSync(f.effectLog,"utf8"),/npm\tdist-tag|git\ttag|gh\trelease create/);const closed=runWorkflowBlock(f,workflowRunBlock("close"),{VERSION:state.version,IDENTITY:state.identity});assert.equal(closed.status,0,closed.stderr);assert.equal(JSON.parse(readFileSync(join(f.root,"state.json"),"utf8")).status,"closed-unpromoted");});

test("production install effect writes durable failure evidence and permits a later success",t=>{const pub=published(),root=mkdtempSync(join(tmpdir(),"slate-install-failure-"));t.after(()=>rmSync(root,{recursive:true,force:true}));const failureOut=join(root,"failure.json");assert.throws(()=>executeInstall({state:pub,expected:owner(pub),runId:"17",runAttempt:"2",workspace:root,out:join(root,"proof.json"),failureOut,exec:()=>{throw new Error("offline install failed");}}));const failure=JSON.parse(readFileSync(failureOut,"utf8"));assert.deepEqual({execution:failure.execution,result:failure.result,failure:failure.failure},{execution:"17:2",result:"failed",failure:"install-command"});const recorded=recordInstallFailure(pub,failure,owner(pub),NOW);let n=0;const proof=executeInstall({state:recorded,expected:owner(recorded),runId:"17",runAttempt:"3",workspace:root,out:join(root,"proof.json"),failureOut:join(root,"later-failure.json"),exec:()=>++n===2?{stdout:'{"type":"response","command":"get_commands","data":{"commands":[{"name":"slate","sourceInfo":{"source":"npm:ytdb-slate@0.10.1"}}]}}\n'}:{stdout:""}});const success=recordInstallProof(recorded,proof,owner(recorded),NOW);assert.equal(success.status,"proved");assert.equal(success.installFailures.length,1);assert.equal(success.installProof.execution,"17:3");});

test("production workflow carries immutable identity through every stage and confines the secret",()=>{const job=(name:string)=>workflow.match(new RegExp(`\\n  ${name}:\\n[\\s\\S]*?(?=\\n  [a-z][a-z-]*:\\n|$)`))?.[0]??"";for(const name of["seal-upload","upload","record-registry","install-proof","record-install-failure","record-proof","promote","record-promotion","finalize"])assert.match(job(name),/--identity/);assert.match(job("registry-proof"),/expected=\{identity:/);for(const name of["recover","recover-promote","recover-promotion-record","abandon","retire","close"])assert.match(job(name),/IDENTITY|--identity/);assert.match(job("prepare"),/--authorization "\$GITHUB_RUN_ID"/);assert.match(job("prepare"),/old_identity.*identity.*status.*!= prepared/);assert.match(job("record-install-failure"),/if: always\(\) && needs\.install-proof\.result == 'failure'/);assert.equal(workflow.split("\n").filter(x=>x.includes("NPM_STAGE_ONLY_TOKEN")).length,2);assert.match(job("upload"),/environment: npm-release[\s\S]*id-token: write/);assert.doesNotMatch(job("promote"),/npm (ci|install|test|pack)/);for(const text of[releasing,agents,mechanism]){assert.match(text,/install-failure-<attempt>/);assert.match(text,/install-failures\//);assert.match(text,/record-install-failure/);}assert.match(releasing,/Do not rerun only `record-install-failure`/);assert.match(releasing,/If installation fails again, the failure recorder uses the same new run attempt\./);assert.match(releasing,/If installation succeeds, the failure recorder is skipped\./);assert.match(releasing,/The release can continue only after the required proofs succeed\./);assert.match(releasing,/dependent jobs can promote `latest` and create final records/);});

test("competing durable writers reject a stale compare-and-swap lease",t=>{const root=mkdtempSync(join(tmpdir(),"slate-cas-"));t.after(()=>rmSync(root,{recursive:true,force:true}));const env={PATH:process.env.PATH??"",HOME:root,GIT_CONFIG_NOSYSTEM:"1",GIT_CONFIG_GLOBAL:"/dev/null"};const run=(cwd:string,...args:string[])=>{const r=spawnSync("git",args,{cwd,env,encoding:"utf8",timeout:10000});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};const remote=join(root,"remote.git"),seed=join(root,"seed");run(root,"init","--bare",remote);mkdirSync(seed);run(seed,"init","-b","main");run(seed,"config","user.name","Test");run(seed,"config","user.email","test@example.invalid");writeFileSync(join(seed,"state"),"one");run(seed,"add","state");run(seed,"commit","-m","seed");run(seed,"remote","add","origin",remote);run(seed,"push","origin","HEAD:release-state");const a=join(root,"a"),b=join(root,"b");run(root,"clone","--branch","release-state",remote,a);run(root,"clone","--branch","release-state",remote,b);for(const d of [a,b]){run(d,"config","user.name","Test");run(d,"config","user.email","test@example.invalid");}const old=run(a,"rev-parse","HEAD");writeFileSync(join(a,"state"),"a");run(a,"commit","-am","a");run(a,"push","origin","HEAD:release-state",`--force-with-lease=refs/heads/release-state:${old}`);writeFileSync(join(b,"state"),"b");run(b,"commit","-am","b");const stale=spawnSync("git",["push","origin","HEAD:release-state",`--force-with-lease=refs/heads/release-state:${old}`],{cwd:b,env,encoding:"utf8",timeout:10000});assert.notEqual(stale.status,0);});

test("exclusive records cannot replace existing evidence",()=>{const root=mkdtempSync(join(tmpdir(),"slate-record-")),path=join(root,"x.json");try{writeExclusive(path,{a:1});assert.throws(()=>writeExclusive(path,{a:2}),/refusing to replace/);assert.deepEqual(JSON.parse(readFileSync(path,"utf8")),{a:1});}finally{rmSync(root,{recursive:true,force:true});}});

function createRosterFixture(t:any,extraPath=false){
  const root=mkdtempSync(join(tmpdir(),"slate-roster-"));t.after(()=>rmSync(root,{recursive:true,force:true}));const repo=join(root,"repo"),bin=join(root,"bin"),evidence=join(root,"evidence");mkdirSync(join(repo,"verification"),{recursive:true});mkdirSync(bin);cpSync(new URL("../verification/release-checks.sh",import.meta.url),join(repo,"verification/release-checks.sh"));chmodSync(join(repo,"verification/release-checks.sh"),0o755);
  const realNode=process.execPath,log=join(root,"fake.log");
  writeFileSync(join(bin,"npm"),`#!/bin/sh\necho "npm $*" >>"$FAKE_LOG"\nif [ "$1 $2" = "test --" ]; then [ "${'${NO_VERDICT:-0}'}" = 1 ] || echo 'RUN VERDICT: WARN — fixture'; fi\nexit 0\n`);
  writeFileSync(join(bin,"bash"),`#!/bin/sh\necho "bash $*" >>"$FAKE_LOG"\ncase "$*" in *"${'${FAKE_FAIL:-__none__}'}"*) exit 7;; esac\ncase "$1" in -c) echo '{"type":"response","command":"get_commands","data":{"commands":[{"name":"slate"}]}}';; esac\nexit 0\n`);
  writeFileSync(join(bin,"node"),`#!/bin/sh\necho "node $*" >>"$FAKE_LOG"\ncase "$1" in -e|-p|--input-type=module) exec ${realNode} "$@";; *) exit 0;; esac\n`);for(const f of ["npm","bash","node"])chmodSync(join(bin,f),0o755);
  const env={PATH:`${bin}:${process.env.PATH??""}`,HOME:root,FAKE_LOG:log,GIT_CONFIG_NOSYSTEM:"1",GIT_CONFIG_GLOBAL:"/dev/null"}; const git=(...a:string[])=>{const r=spawnSync("git",a,{cwd:repo,env,encoding:"utf8",timeout:10000});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
  spawnSync("git",["init","-b","main",repo],{env,encoding:"utf8"});git("config","user.name","Test");git("config","user.email","test@example.invalid");writeFileSync(join(repo,"package.json"),'{"version":"0.10.0"}\n');writeFileSync(join(repo,"package-lock.json"),'{"version":"0.10.0","packages":{"":{"version":"0.10.0"}}}\n');git("add",".");git("commit","-m","base");const base=git("rev-parse","HEAD");const r=req();mkdirSync(join(repo,"release/requests/0.10.1"),{recursive:true});writeFileSync(join(repo,"package.json"),'{"version":"0.10.1"}\n');writeFileSync(join(repo,"package-lock.json"),'{"version":"0.10.1","packages":{"":{"version":"0.10.1"}}}\n');writeFileSync(join(repo,"release/requests/0.10.1/request.json"),JSON.stringify(r));writeFileSync(join(repo,"release/requests/0.10.1/notes.md"),notes);writeFileSync(join(repo,"release/requests/0.10.1/coverage.json"),JSON.stringify({schema:2,parentPolicy:"exact-release-parent",allowedPaths:r.coverageDisposition.allowedPaths,verdict:"WARN"}));if(extraPath)writeFileSync(join(repo,"extra"),"x");git("add",".");git("commit","-m","release");return{root,repo,evidence,base,request:join(repo,"release/requests/0.10.1/request.json"),env};
}
function runRoster(f:any,more:any={}){return spawnSync("/bin/bash",["verification/release-checks.sh","--repo",f.repo,"--base",f.base,"--request",f.request,"--evidence",f.evidence],{cwd:f.repo,env:{...f.env,...more},encoding:"utf8",timeout:30000});}

test("real release roster executes every command in order with strict flags and reviewed WARN",t=>{const f=createRosterFixture(t);const r=runRoster(f);assert.equal(r.status,0,r.stderr+r.stdout);const commands=readFileSync(join(f.evidence,"commands.tsv"),"utf8");assert.match(commands,/^typecheck\tnpm run typecheck/m);assert.match(commands,/resolver.*--strict/);assert.match(commands,/ladder.*--strict/);assert.equal(commands.trim().split("\n").length,14);assert.match(readFileSync(join(f.evidence,"coverage-disposition.txt"),"utf8"),new RegExp(req().identity));});

test("real release roster propagates command failure and rejects missing verdict or foreign WARN paths",t=>{let f=createRosterFixture(t);let r=runRoster(f,{FAKE_FAIL:"run-resolver-checks"});assert.equal(r.status,7);f=createRosterFixture(t);r=runRoster(f,{NO_VERDICT:"1"});assert.equal(r.status,2);f=createRosterFixture(t,true);r=runRoster(f);assert.equal(r.status,2);});

test("roster production contract names the real typecheck command",()=>{const source=readFileSync(new URL("../verification/release-checks.sh",import.meta.url),"utf8");assert.match(source,/^run typecheck npm run typecheck$/m);});
