#!/usr/bin/env node
import { createHash } from "node:crypto";
import { constants, openSync, closeSync, linkSync, readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { basename, resolve } from "node:path";
import process from "node:process";

export const SCHEMA = 2;
export const INTERNAL_TAG = "slate-candidate";
export const STATUSES = Object.freeze(["prepared", "claimed", "checking", "ready", "upload-unknown", "published", "proved", "promotion-unknown", "promoted", "complete", "abandoned", "retired", "mismatch", "closed-unpromoted"]);
export const TERMINAL = Object.freeze(["complete", "abandoned", "retired", "mismatch", "closed-unpromoted"]);
const SHA=/^[0-9a-f]{40}$/, VERSION=/^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/, HASH=/^[0-9a-f]{64}$/, AUTH=/^[1-9][0-9]*$/;
const metadataPaths=v=>[`release/requests/${v}/coverage.json`,`release/requests/${v}/notes.md`,`release/requests/${v}/request.json`];
const stable=value=>JSON.stringify(value,(_key,item)=>item&&typeof item==="object"&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item);
const plain=(value,label)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${label} must be an object`);return value;};
export const hashBytes=bytes=>({sha256:createHash("sha256").update(bytes).digest("hex"),integrity:`sha512-${createHash("sha512").update(bytes).digest("base64")}`});
export function assertVersion(value){if(!VERSION.test(value))throw new Error(`invalid release version: ${JSON.stringify(value)}`);return value;}
export function assertSha(value,label="SHA"){if(!SHA.test(value))throw new Error(`${label} must be a full lowercase commit SHA`);return value;}
export const executionKey=(runId,runAttempt)=>{if(!AUTH.test(String(runId))||!AUTH.test(String(runAttempt)))throw new Error("run id and run attempt must be positive integers");return `${runId}:${runAttempt}`;};

export function makeRequest({version,baseSha,notes,currentVersion,authorization}){
  assertVersion(version);assertSha(baseSha,"baseSha");if(typeof notes!=="string"||!notes.trim())throw new Error("release notes must not be empty");if(!AUTH.test(String(authorization)))throw new Error("authorization must be the preparation run id");
  const allowedPaths=metadataPaths(version);if(currentVersion!==version)allowedPaths.unshift("package-lock.json","package.json");
  const core={schema:SCHEMA,version,baseSha,authorization:String(authorization),notesSha256:hashBytes(Buffer.from(notes)).sha256,coverageDisposition:{verdict:"WARN",parentPolicy:"exact-release-parent",allowedPaths}};
  return validateRequest({...core,identity:hashBytes(Buffer.from(stable(core))).sha256});
}
export function validateRequest(input){
  const r=plain(input,"request");assertVersion(r.version);assertSha(r.baseSha,"request baseSha");if(r.schema!==SCHEMA||!AUTH.test(r.authorization)||!HASH.test(r.notesSha256)||!HASH.test(r.identity))throw new Error("request schema, authorization, or hashes are malformed");
  const d=plain(r.coverageDisposition,"coverage disposition");if(d.verdict!=="WARN"||d.parentPolicy!=="exact-release-parent"||!Array.isArray(d.allowedPaths))throw new Error("coverage disposition is malformed");
  const three=metadataPaths(r.version),five=["package-lock.json","package.json",...three];if(![JSON.stringify(three),JSON.stringify(five)].includes(JSON.stringify(d.allowedPaths)))throw new Error("coverage paths must be the exact metadata-only release set");
  const {identity,...core}=r;if(hashBytes(Buffer.from(stable(core))).sha256!==identity)throw new Error("request identity is invalid");return r;
}
export function initialState(request,now){const r=validateRequest(request);return validateState({schema:SCHEMA,version:r.version,identity:r.identity,status:"prepared",upload:"none",promotion:"none",requestBaseSha:r.baseSha,releaseSha:null,releaseParent:null,pullRequest:null,claimExecution:null,uploadExecution:null,promoterExecution:null,artifact:null,registry:null,installFailures:[],installProof:null,promotionEvidence:null,tag:`v${r.version}`,internalTag:INTERNAL_TAG,createdAt:now,updatedAt:now});}
export function validateState(input){
  const s=plain(input,"state");if(s.schema!==SCHEMA)throw new Error("unsupported state schema");assertVersion(s.version);if(!HASH.test(s.identity))throw new Error("state identity is malformed");if(!STATUSES.includes(s.status))throw new Error(`unknown release status: ${s.status}`);if(!["none","unknown","verified","mismatch","observed-absent"].includes(s.upload))throw new Error("unknown upload state");if(!["none","unknown","verified","conflict","superseded","refused"].includes(s.promotion))throw new Error("unknown promotion state");if(!Array.isArray(s.installFailures))throw new Error("install failure history is malformed");assertSha(s.requestBaseSha,"requestBaseSha");for(const k of ["releaseSha","releaseParent"])if(s[k]!==null)assertSha(s[k],k);if(s.tag!==`v${s.version}`||s.internalTag!==INTERNAL_TAG)throw new Error("state tags disagree");if(s.status==="upload-unknown"&&s.upload!=="unknown")throw new Error("upload-unknown status needs unknown upload");if(["published","proved","promotion-unknown","promoted","complete","closed-unpromoted"].includes(s.status)&&s.upload!=="verified")throw new Error("published lifecycle needs verified upload");if(s.status==="mismatch"&&s.upload!=="mismatch")throw new Error("mismatch state needs mismatch evidence");if(s.upload==="observed-absent"&&(s.status!=="retired"||s.absence?.identity!==s.identity||s.absence?.releaseSha!==s.releaseSha||s.absence?.execution!==s.uploadExecution||!s.artifact))throw new Error("observed absence needs retired state and sealed evidence");if(["promoted","complete"].includes(s.status)&&s.promotion!=="verified")throw new Error("promoted lifecycle needs verified promotion");return s;
}
const clone=s=>structuredClone(validateState(s)),stamp=(s,now)=>({...s,updatedAt:now});
function owner(s,expected,{claimed=true}={}){const e=plain(expected,"expected release owner");if(s.identity!==e.identity||s.version!==e.version)throw new Error("expected release identity does not own the lane");if(claimed&&(s.releaseSha!==e.releaseSha||s.releaseParent!==e.releaseParent))throw new Error("expected release commit does not own the lane");return s;}
export const releaseOwner=s=>({identity:s.identity,version:s.version,releaseSha:s.releaseSha,releaseParent:s.releaseParent});
export function claimRelease(input,{request,releaseSha,parentSha,pullRequest,runId,runAttempt},now){const s=clone(input),r=validateRequest(request),key=executionKey(runId,runAttempt);if(s.identity!==r.identity||s.version!==r.version)throw new Error("merged request does not match durable owner");assertSha(releaseSha,"releaseSha");assertSha(parentSha,"parentSha");if(s.status==="claimed"){if(s.releaseSha===releaseSha&&s.releaseParent===parentSha&&s.pullRequest===pullRequest)return s;throw new Error("another release claim already owns the lane");}if(s.status!=="prepared")throw new Error("prepared release is required for claim");return validateState(stamp({...s,status:"claimed",releaseSha,releaseParent:parentSha,pullRequest,claimExecution:key},now));}
export function advance(input,next,expected,now){const s=owner(clone(input),expected),edges={claimed:"checking",checking:"ready",published:"proved",promoted:"complete"};if(edges[s.status]!==next)throw new Error(`invalid release transition: ${s.status} -> ${next}`);return validateState(stamp({...s,status:next},now));}
export function beginUpload(input,artifact,expected,runId,runAttempt,now){const s=owner(clone(input),expected),key=executionKey(runId,runAttempt);if(s.status!=="ready"||s.upload!=="none")throw new Error("one ready release with no upload attempt is required");if(!artifact||!HASH.test(artifact.sha256)||!/^sha512-/.test(artifact.integrity)||basename(artifact.file)!==artifact.file)throw new Error("artifact evidence is malformed");return validateState(stamp({...s,status:"upload-unknown",upload:"unknown",uploadExecution:key,artifact:{...artifact,identity:s.identity,releaseSha:s.releaseSha,execution:key}},now));}
export function authorizeUpload(input,expected,runId,runAttempt){const s=owner(validateState(input),expected),key=executionKey(runId,runAttempt);if(s.status!=="upload-unknown"||s.upload!=="unknown"||s.uploadExecution!==key||s.artifact?.identity!==s.identity||s.artifact?.releaseSha!==s.releaseSha||s.artifact?.execution!==key)throw new Error("this workflow execution is not the sealed upload authority");return{...releaseOwner(s),internalTag:s.internalTag,artifact:s.artifact,execution:key};}
export function classifyRegistry(input,localBytes,registryBytes,metadata,expected){const s=owner(validateState(input),expected);if(s.upload!=="unknown"||!s.artifact||s.artifact.identity!==s.identity||s.artifact.execution!==s.uploadExecution)throw new Error("registry proof needs the expected unknown upload and saved artifact");const local=hashBytes(localBytes);if(local.sha256!==s.artifact.sha256||local.integrity!==s.artifact.integrity)throw new Error("saved artifact no longer matches evidence");const integrity=metadata?.integrity??metadata?.["dist.integrity"]??metadata?.dist?.integrity;const envelope={identity:s.identity,releaseSha:s.releaseSha,execution:s.uploadExecution};if(!metadata||metadata.version!==s.version||typeof integrity!=="string")return{...envelope,result:"inconclusive",upload:"unknown"};if(integrity!==local.integrity||!Buffer.from(localBytes).equals(Buffer.from(registryBytes)))return{...envelope,result:"mismatch",upload:"mismatch",servedIntegrity:integrity,attribution:"unknown"};return{...envelope,result:"verified",upload:"verified",integrity:local.integrity};}
export function recordRegistry(input,result,expected,now){const s=owner(clone(input),expected);if(s.status!=="upload-unknown"||s.upload!=="unknown"||result.identity!==s.identity||result.releaseSha!==s.releaseSha||result.execution!==s.uploadExecution)throw new Error("registry result does not belong to the active upload");if(result.result==="verified")return validateState(stamp({...s,status:"published",upload:"verified",registry:result},now));if(result.result==="mismatch")return validateState(stamp({...s,status:"mismatch",upload:"mismatch",registry:result},now));throw new Error("inconclusive registry evidence stays unknown");}
export function authorizeInstall(input,expected,runId,runAttempt){const s=owner(validateState(input),expected),execution=executionKey(runId,runAttempt),r=s.registry;if(s.status!=="published"||s.upload!=="verified"||r?.result!=="verified"||r?.identity!==s.identity||r?.releaseSha!==s.releaseSha||r?.execution!==s.uploadExecution||typeof r?.integrity!=="string")throw new Error("install proof needs the exact verified publication");return{...releaseOwner(s),execution,registryIntegrity:r.integrity};}
const installResultBelongs=(s,envelope)=>{const r=s.registry;return envelope?.identity===s.identity&&envelope?.version===s.version&&envelope?.releaseSha===s.releaseSha&&envelope?.releaseParent===s.releaseParent&&/^([1-9][0-9]*):([1-9][0-9]*)$/.test(envelope?.execution??"")&&envelope?.registryIntegrity===r?.integrity&&r?.result==="verified"&&r?.identity===s.identity&&r?.releaseSha===s.releaseSha&&r?.execution===s.uploadExecution;};
export function recordInstallFailure(input,envelope,expected,now){const s=owner(clone(input),expected);if(s.status!=="published"||s.upload!=="verified"||!installResultBelongs(s,envelope)||envelope?.result!=="failed"||!["install-command","command-proof"].includes(envelope?.failure))throw new Error("install failure does not belong to the verified publication");if(s.installFailures.some(x=>x.execution===envelope.execution))return s;return validateState(stamp({...s,installFailures:[...s.installFailures,envelope]},now));}
export function recordInstallProof(input,envelope,expected,now){const s=owner(clone(input),expected),proof=envelope?.proof;if(s.status!=="published"||s.upload!=="verified"||!installResultBelongs(s,envelope))throw new Error("install proof does not belong to the verified publication");if(proof?.command!=="slate"||proof?.source!==`npm:ytdb-slate@${s.version}`)throw new Error("install proof is malformed");return validateState(stamp({...s,status:"proved",installProof:envelope},now));}
export function beginPromotion(input,expectedLatest,expected,runId,runAttempt,now){const s=owner(clone(input),expected);if(s.status!=="proved"||!["none","conflict","superseded","refused"].includes(s.promotion))throw new Error("proved active release with resolved promotion is required");assertVersion(expectedLatest);const execution=executionKey(runId,runAttempt);return validateState(stamp({...s,status:"promotion-unknown",promotion:"unknown",promoterExecution:execution,promotionEvidence:{identity:s.identity,releaseSha:s.releaseSha,execution,expectedLatest,intentAt:now}},now));}
export function authorizePromotion(input,expected,runId,runAttempt){const s=owner(validateState(input),expected),key=executionKey(runId,runAttempt),e=s.promotionEvidence;if(s.status!=="promotion-unknown"||s.promotion!=="unknown"||s.promoterExecution!==key||e?.identity!==s.identity||e?.releaseSha!==s.releaseSha||e?.execution!==key)throw new Error("this execution is not the active promoter");return{...releaseOwner(s),expectedLatest:e.expectedLatest,internalTag:s.internalTag,execution:key};}
export function recordPromotion(input,result,expected,now){const s=owner(clone(input),expected);if(s.status!=="promotion-unknown"||s.promotion!=="unknown"||result.identity!==s.identity||result.releaseSha!==s.releaseSha||result.execution!==s.promoterExecution)throw new Error("promotion result does not belong to the active promoter");if(result.result==="verified"&&result.after===s.version)return validateState(stamp({...s,status:"promoted",promotion:"verified",promotionEvidence:{...s.promotionEvidence,...result}},now));if(["conflict","superseded","refused"].includes(result.result))return validateState(stamp({...s,status:"proved",promotion:result.result,promotionEvidence:{...s.promotionEvidence,...result},promoterExecution:null},now));throw new Error("unresolved promotion outcome remains blocking");}
export function abandon(input,target,merged,now){const s=owner(clone(input),target,{claimed:false});if(s.status!=="prepared"||s.upload!=="none"||merged)throw new Error("only the exact unmerged prepared request can be abandoned");return validateState(stamp({...s,status:"abandoned"},now));}
// Date.parse accepts strings such as "0" and normalizes invalid calendar dates. Registry evidence needs a complete ISO timestamp for each listed version.
const ISO_TIME=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(?:Z|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/;
function dated(value){
  if(typeof value!=="string")return false;
  const match=ISO_TIME.exec(value);if(!match||!Number.isFinite(Date.parse(value)))return false;
  const [,year,month,day,hour,minute,second]=match.map(Number),calendar=new Date(0);
  calendar.setUTCFullYear(year,month-1,day);calendar.setUTCHours(hour,minute,second,0);
  return calendar.getUTCFullYear()===year&&calendar.getUTCMonth()===month-1&&calendar.getUTCDate()===day&&calendar.getUTCHours()===hour&&calendar.getUTCMinutes()===minute&&calendar.getUTCSeconds()===second;
}
export function versionUsage(input,version,{requireEarlier=false}={}){const p=plain(input,"full package document");assertVersion(version);if(Object.hasOwn(p,"error"))throw new Error("full package document reports an error");if(!Array.isArray(p.versions)||!p.versions.length||!p.versions.every(v=>typeof v==="string"&&VERSION.test(v)))throw new Error("full package document needs versions");const time=plain(p.time,"full package publication time");if(!dated(time.created)||!dated(time.modified)||!p.versions.every(v=>dated(time[v]))||requireEarlier&&!p.versions.some(v=>v!==version))throw new Error("full package document needs dated versions and time");return p.versions.includes(version)||Object.hasOwn(time,version);}
export function retire(input,target,now,evidence){const s=owner(clone(input),target);if(["claimed","checking","ready"].includes(s.status)&&s.upload==="none")return validateState(stamp({...s,status:"retired"},now));if(s.status!=="upload-unknown"||s.upload!=="unknown")throw new Error("only the exact inactive merged authorization or unknown upload can retire");const e=plain(evidence,"absence evidence"),run=plain(e.run,"upload run"),job=plain(e.job,"upload job");if(!s.artifact||s.artifact.identity!==s.identity||s.artifact.releaseSha!==s.releaseSha||s.artifact.execution!==s.uploadExecution||!AUTH.test(String(run.id))||!AUTH.test(String(run.run_attempt))||`${run.id}:${run.run_attempt}`!==s.uploadExecution||run.status!=="completed")throw new Error("sealed upload run attempt has not completed");if(job.name!=="upload"||job.status!=="completed"||!(["failure","cancelled","timed_out","action_required","neutral","skipped","stale"].includes(job.conclusion))||job.run_id!==run.id||job.run_attempt!==run.run_attempt)throw new Error("sealed upload job must complete without success");const finished=Date.parse(job.completed_at),observed=Date.parse(now);if(!Number.isFinite(finished)||!Number.isFinite(observed)||observed-finished<60*60*1000)throw new Error("upload job needs 60 minutes of settled time");if(versionUsage(e.package,s.version,{requireEarlier:true}))throw new Error("npm already records the release version in versions or time");const absence={identity:s.identity,releaseSha:s.releaseSha,execution:s.uploadExecution,runId:run.id,attempt:run.run_attempt,jobId:job.id,conclusion:job.conclusion,completedAt:job.completed_at,observedAt:now,registryCreatedAt:e.package.time.created,earlierVersions:e.package.versions.length};return validateState(stamp({...s,status:"retired",upload:"observed-absent",absence},now));}
export function closeWithoutPromotion(input,target,now){const s=owner(clone(input),target),promotionResolved=["none","conflict","superseded","refused"].includes(s.promotion)&&!s.promoterExecution,proved=s.status==="proved",failedPublished=s.status==="published"&&s.installFailures.some(x=>installResultBelongs(s,x)&&x.result==="failed"&&["install-command","command-proof"].includes(x.failure));if(s.upload!=="verified"||!promotionResolved||(!proved&&!failedPublished))throw new Error("proved release or published release with recorded install failure and no active or unresolved promotion is required");return validateState(stamp({...s,status:"closed-unpromoted"},now));}
export function planFinalization({state:input,expected,remoteTagSha,releaseTarget}){const s=owner(validateState(input),expected);if(s.status!=="promoted"||s.promotion!=="verified"||!s.installProof)throw new Error("verified promotion and install proof must finish before finalization");if(remoteTagSha&&remoteTagSha!==s.releaseSha)throw new Error("existing tag points at another commit");if(releaseTarget&&releaseTarget!==s.releaseSha)throw new Error("existing GitHub release points at another commit");return{createTag:!remoteTagSha,createRelease:!releaseTarget,tag:s.tag,target:s.releaseSha};}
export function verifyReleaseIdentity({request,durableRequest,coverageRecord,notes,releaseSha,parentSha,changedPaths,manifestVersion,associatedPullRequests}){const r=validateRequest(request),d=validateRequest(durableRequest);if(r.identity!==d.identity||JSON.stringify(r)!==JSON.stringify(d))throw new Error("merged request differs from durable owner request");assertSha(releaseSha,"releaseSha");assertSha(parentSha,"parentSha");if(hashBytes(Buffer.from(notes)).sha256!==r.notesSha256)throw new Error("reviewed release notes changed");if(manifestVersion!==r.version)throw new Error("release manifest version disagrees with request");const expected={schema:SCHEMA,parentPolicy:r.coverageDisposition.parentPolicy,allowedPaths:r.coverageDisposition.allowedPaths,verdict:"WARN"};if(JSON.stringify(coverageRecord)!==JSON.stringify(expected))throw new Error("coverage disposition disagrees with request");if(JSON.stringify([...changedPaths].sort())!==JSON.stringify([...r.coverageDisposition.allowedPaths].sort()))throw new Error("release diff is not the exact reviewed metadata diff");const merged=associatedPullRequests.filter(p=>p?.merged===true&&p?.mergeCommitSha===releaseSha&&p?.baseRefName==="main");if(merged.length!==1)throw new Error("release commit needs exactly one associated merged pull request into main");return{identity:r.identity,version:r.version,releaseSha,parentSha,pullRequest:merged[0].number,notesSha256:r.notesSha256,allowedPaths:r.coverageDisposition.allowedPaths};}
export function writeExclusive(path,value){const target=resolve(path),temp=`${target}.tmp-${process.pid}`;let fd;try{fd=openSync(temp,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY,0o600);writeFileSync(fd,`${JSON.stringify(value,null,2)}\n`);closeSync(fd);fd=undefined;try{linkSync(temp,target);}catch(e){if(e?.code==="EEXIST")throw new Error(`refusing to replace existing record: ${target}`);throw e;}unlinkSync(temp);}finally{if(fd!==undefined)closeSync(fd);try{unlinkSync(temp);}catch(e){if(e?.code!=="ENOENT")throw e;}}}
const readJson=p=>JSON.parse(readFileSync(p,"utf8"));const args=xs=>{const o={_:[]};for(let i=0;i<xs.length;i++){if(!xs[i].startsWith("--"))o._.push(xs[i]);else o[xs[i].slice(2)]=xs[++i];}return o;};
const expected=a=>({identity:a.identity,version:a.version,releaseSha:a.sha||null,releaseParent:a.parent||null});
async function main(){const[cmd,...rest]=process.argv.slice(2),a=args(rest),now=new Date().toISOString();if(!cmd||cmd==="--help"){console.log("release-control commands: make-request state-init claim advance begin-upload registry-record install-failure-record install-record promotion-intent promotion-record abandon retire close plan-finalization");return;}let out,e=expected(a);if(cmd==="make-request")out=makeRequest({version:a.version,baseSha:a.base,notes:readFileSync(a.notes,"utf8"),currentVersion:a["current-version"],authorization:a.authorization});else if(cmd==="state-init")out=initialState(readJson(a.request),now);else if(cmd==="claim")out=claimRelease(readJson(a.state),{request:readJson(a.request),releaseSha:a.sha,parentSha:a.parent,pullRequest:Number(a.pr),runId:a["run-id"],runAttempt:a["run-attempt"]},now);else if(cmd==="advance")out=advance(readJson(a.state),a.next,e,now);else if(cmd==="begin-upload"){const b=readFileSync(a.archive);out=beginUpload(readJson(a.state),{file:basename(a.archive),...hashBytes(b)},e,a["run-id"],a["run-attempt"],now);}else if(cmd==="registry-record")out=recordRegistry(readJson(a.state),readJson(a.result),e,now);else if(cmd==="install-failure-record")out=recordInstallFailure(readJson(a.state),readJson(a.failure),e,now);else if(cmd==="install-record")out=recordInstallProof(readJson(a.state),readJson(a.proof),e,now);else if(cmd==="promotion-intent")out=beginPromotion(readJson(a.state),a.latest,e,a["run-id"],a["run-attempt"],now);else if(cmd==="promotion-record")out=recordPromotion(readJson(a.state),readJson(a.result),e,now);else if(cmd==="abandon")out=abandon(readJson(a.state),e,a.merged==="true",now);else if(cmd==="retire")out=retire(readJson(a.state),e,now,a.evidence?readJson(a.evidence):undefined);else if(cmd==="close")out=closeWithoutPromotion(readJson(a.state),e,now);else if(cmd==="plan-finalization"){process.stdout.write(JSON.stringify(planFinalization({state:readJson(a.state),expected:e,remoteTagSha:a["tag-sha"]||"",releaseTarget:a["release-target"]||""}))+"\n");return;}else throw new Error(`unknown command: ${cmd}`);writeExclusive(a.out,out);}
if(resolve(process.argv[1]??"")===resolve(new URL(import.meta.url).pathname))main().catch(e=>{console.error(`release-control: ${e.message}`);process.exitCode=2;});
