#!/usr/bin/env node
import { execFileSync, spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, resolve } from "node:path";
import process from "node:process";
import { authorizeInstall, authorizePromotion, authorizeUpload, hashBytes, planFinalization } from "./release-control.mjs";
const readJson=p=>JSON.parse(readFileSync(p,"utf8"));
const run=(command,args,options={})=>{const r=spawnSync(command,args,{encoding:"utf8",timeout:120000,...options});if(r.error)throw r.error;if(r.status!==0){const error=new Error(`${command} failed with status ${r.status}: ${r.stderr??""}`);error.stderr=r.stderr??"";error.status=r.status;throw error;}return r;};
const capture=(command,args,options={})=>execFileSync(command,args,{encoding:"utf8",timeout:120000,...options}).trim();
const args=xs=>{const x={_:[]};for(let i=0;i<xs.length;i++){if(xs[i].startsWith("--"))x[xs[i].slice(2)]=xs[++i];else x._.push(xs[i]);}return x;};
const requireNoToken=()=>{for(const k of Object.keys(process.env))if(/NODE_AUTH_TOKEN|NPM_TOKEN|PROMOTION_TOKEN/i.test(k))throw new Error(`credential ${k} is forbidden in this job`);};
const expected=a=>({identity:a.identity,version:a.version,releaseSha:a.sha,releaseParent:a.parent});
export function executeUpload({state,expected:owner,archive,runId,runAttempt,registry,npmVersion=()=>capture("npm",["--version"]),exec=run}){const auth=authorizeUpload(state,owner,runId,runAttempt),file=resolve(archive);if(!statSync(file).isFile())throw new Error("upload archive must be an existing regular file");const actual=hashBytes(readFileSync(file)),[major,minor,patch]=npmVersion().split(".").map(Number);if(major<11||(major===11&&(minor<5||(minor===5&&patch<1))))throw new Error("npm 11.5.1 or newer is required");if(basename(file)!==auth.artifact.file||actual.sha256!==auth.artifact.sha256||actual.integrity!==auth.artifact.integrity)throw new Error("sealed archive bytes differ");exec("npm",["publish",file,"--tag",auth.internalTag,"--ignore-scripts","--provenance=false","--registry",registry]);return auth;}
export function executePromotion({state,expected:owner,runId,runAttempt,registry,token,view=r=>capture("npm",["view","ytdb-slate","dist-tags.latest","--registry",r]),exec=run}){const auth=authorizePromotion(state,owner,runId,runAttempt),envelope={identity:auth.identity,releaseSha:auth.releaseSha,execution:auth.execution};if(!token)return{...envelope,result:"not-attempted",cause:"missing-token"};let before;try{before=view(registry);}catch{return{...envelope,result:"not-attempted",cause:"latest-read-failed"};}if(before!==auth.expectedLatest)return{...envelope,result:"conflict",before,expected:auth.expectedLatest,after:before};try{exec("npm",["dist-tag","add",`ytdb-slate@${auth.version}`,"latest","--registry",registry],{env:{...process.env,NODE_AUTH_TOKEN:token}});}catch(error){if(/(?:E401|E403|401 Unauthorized|403 Forbidden)/.test(String(error?.stderr??error?.message)))return{...envelope,result:"refused",before,after:before};throw error;}const after=view(registry);if(after!==auth.version)throw new Error(`promotion outcome is unresolved: latest is ${after}`);return{...envelope,result:"verified",before,after};}
export function executeInstall({state,expected:owner,runId,runAttempt,workspace,out,failureOut,exec=run}){requireNoToken();const auth=authorizeInstall(state,owner,runId,runAttempt),root=resolve(workspace);mkdirSync(root,{recursive:true});const project=`${root}/project`,agent=`${root}/agent`,cache=`${root}/cache`;for(const p of[project,agent,cache])mkdirSync(p,{recursive:true});const pi=process.env.PI_BIN||"pi",baseEnv={PATH:process.env.PATH??"",HOME:root,PI_CODING_AGENT_DIR:agent,npm_config_cache:cache,npm_config_registry:process.env.REGISTRY??"https://registry.npmjs.org/"};let failure="install-command";try{exec(pi,["install","-l",`npm:ytdb-slate@${state.version}`,"-a"],{cwd:project,env:baseEnv});failure="command-proof";const rpc=exec(pi,["--mode","rpc","-a"],{cwd:project,env:{...baseEnv,PI_OFFLINE:"1"},input:'{"id":"1","type":"get_commands"}\n'});const events=String(rpc?.stdout??"").trim().split("\n").filter(Boolean).map(JSON.parse),response=events.find(x=>x.type==="response"&&x.command==="get_commands"),commands=response?.data?.commands?.filter(x=>x.name==="slate");if(events.some(x=>x.type==="extension_error")||commands?.length!==1)throw new Error("installed extension did not register one /slate command");const proof={...auth,proof:{command:"slate",source:commands[0].sourceInfo?.source}};if(proof.proof.source!==`npm:ytdb-slate@${state.version}`)throw new Error("installed extension source differs from exact version");writeFileSync(out,JSON.stringify(proof,null,2)+"\n");return proof;}catch(error){if(failureOut)writeFileSync(failureOut,JSON.stringify({...auth,result:"failed",failure},null,2)+"\n");throw error;}}
export function executeFinalRecords({state,expected:owner,notes,repo,tagSha="",releaseTarget="",exec=run}){requireNoToken();const plan=planFinalization({state,expected:owner,remoteTagSha:tagSha,releaseTarget});if(plan.createTag)exec("git",["tag",plan.tag,plan.target]);if(plan.createTag)exec("git",["push","origin",`refs/tags/${plan.tag}`]);if(plan.createRelease)exec("gh",["release","create",plan.tag,"--repo",repo,"--verify-tag","--target",plan.target,"--title",`ytdb-slate ${state.version}`,"--notes-file",notes]);return plan;}
async function main(){const[cmd,...rest]=process.argv.slice(2),a=args(rest),state=a.state?readJson(a.state):null,owner=expected(a);if(!cmd||cmd==="--help"){console.log("release-job commands: upload promote install final-records");return;}if(cmd==="upload")executeUpload({state,expected:owner,archive:a.archive,runId:a["run-id"],runAttempt:a["run-attempt"],registry:a.registry});else if(cmd==="promote"){const result=executePromotion({state,expected:owner,runId:a["run-id"],runAttempt:a["run-attempt"],registry:a.registry,token:process.env.NODE_AUTH_TOKEN});writeFileSync(a.out,JSON.stringify(result,null,2)+"\n");if(result.result==="not-attempted")console.log(`::error::Promotion not-attempted (${result.cause}): no npm write happened`);}else if(cmd==="install")executeInstall({state,expected:owner,runId:a["run-id"],runAttempt:a["run-attempt"],workspace:a.workspace,out:a.out,failureOut:a["failure-out"]});else if(cmd==="final-records")executeFinalRecords({state,expected:owner,notes:a.notes,repo:a.repo,tagSha:a["tag-sha"]||"",releaseTarget:a["release-target"]||""});else throw new Error(`unknown command: ${cmd}`);}
if(resolve(process.argv[1]??"")===resolve(new URL(import.meta.url).pathname))main().catch(e=>{console.error(`release-job: ${e.message}`);process.exitCode=2;});
